// Keeps the web boot screen identical to the Mac app's: inlines macos/loading.css and
// macos/loading-svg.html into index.html between the BB-BOOT markers. Runs before every build.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const css = (await fs.readFile(path.join(root, 'macos/loading.css'), 'utf8')).trim();
const scene = (await fs.readFile(path.join(root, 'macos/loading-svg.html'), 'utf8')).trim();
const bars = '<i></i>'.repeat(12);
const block = `<!-- BB-BOOT:START (generated by scripts/sync-loading.mjs from macos/loading.*) -->
    <style>${css}</style>
    <div id="bb-boot" role="status" aria-live="polite">${scene}<div class="bb-box"><p class="bb-name">BrainBook</p><p class="bb-tag">IDEAS · FOR · HERMES</p><p class="bb-msg" id="bb-msg">Loading your brain</p><div class="bb-bar">${bars}</div></div></div>
    <!-- BB-BOOT:END -->`;

const file = path.join(root, 'index.html');
let html = await fs.readFile(file, 'utf8');
if (html.includes('<!-- BB-BOOT:START')) {
  html = html.replace(/<!-- BB-BOOT:START[\s\S]*?<!-- BB-BOOT:END -->/, block);
} else {
  // First run: replace the old hand-written boot style and markup.
  html = html.replace(/\s*<style>#bb-boot[\s\S]*?<\/style>/, '');
  html = html.replace(/<div id="bb-boot"[\s\S]*?<\/div>\s*(?=<div id="root")/, `${block}\n    `);
}
if (!html.includes('BB-BOOT:START')) throw new Error('index.html: could not place the boot screen');
await fs.writeFile(file, html);
console.log('boot screen synced');
